# Generated by Django 4.2 on 2023-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=256)),
                ('post_des', models.TextField()),
                ('post_image', models.URLField()),
                ('post_date', models.DateTimeField()),
            ],
        ),
    ]
