# Generated by Django 4.2 on 2023-11-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user_id',
        ),
    ]
