# Generated by Django 4.2 on 2023-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logintest',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pw', models.TextField()),
                ('user_nkn', models.CharField(max_length=30)),
                ('user_register', models.DateTimeField()),
            ],
        ),
    ]
