# Generated by Django 4.2 on 2023-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_pic',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
