# Generated by Django 4.2 on 2023-11-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customuser_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('authtoken.token',),
        ),
    ]
